Repository elementor/one-click-accessibility, pull requests merged in 2025-08, with the labels that each got.

#363 [APP-1766] Remove visit quota indications
  modules/settings/assets/js/app.js
  modules/settings/assets/js/components/quota-bar/quota-bar-group.js
  modules/settings/assets/js/components/quota-bar/quota-indicator.js
  modules/settings/module.php
  modules/settings/notices/quota-100.php
Labels: ui, 1 min review, 🚨 1 Unresolved Thread(s)

#344 [APP-1730] Add info details
  modules/settings/assets/js/components/analytics/analytics-toggle.js
  modules/settings/assets/js/components/analytics/charts-list.js
  modules/settings/assets/js/components/sidebar-menu/menu.js
  modules/settings/assets/js/components/sidebar-menu/tooltips/analytics.js
  modules/settings/assets/js/contexts/analytics-context.js
Labels: enhancement, ui, 20 min review, 🚨 1 Unresolved Thread(s)

#364 Tweak: WPML Support [APP-1795]
  modules/connect/classes/utils.php
  modules/widget/components/cache-compatibility.php
Labels: 1 min review

#368 [APP-1831] Update tooltip text
  modules/settings/assets/js/pages/assistant/stats/index.js
Labels: update, 1 min review

#370 [APP-1832] Fix scan dashboard UI width
  modules/settings/assets/js/pages/assistant/index.js
Labels: ui, fix, 1 min review

#373 [APP-1843][1845] fix issue with draft page url, prevent error for gradient
  modules/remediation/classes/utils.php
  modules/scanner/assets/js/components/color-contrast-form/index.js
  modules/scanner/assets/js/layouts/color-contrast-layout.js
  modules/scanner/module.php
Labels: 10 min review

#379 Tweak: Update webpack config to optimize local builds [n/a]
  package.json
  webpack.config.js
Labels: 1 min review, missing-jira, 🚨 1 Unresolved Thread(s)

#381 Fix: Handle the unhandled exception in the Client [APP-1780]
  classes/services/client.php
  modules/settings/module.php
Labels: 1 min review

#385 [APP-0000] Fix disable manage btn in dashboard, resolve issue with wp…
  modules/remediation/components/cache-cleaner.php
  modules/remediation/database/page-entry.php
  modules/remediation/database/remediation-entry.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#384 [APP-1804] Added support for php 8.4
  classes/database/entry.php
  classes/database/table.php
  modules/remediation/database/remediation-entry.php
Labels: update, 1 min review, compatibility

#387 [APP-1865] add clear cache button
  modules/remediation/module.php
  modules/remediation/rest/clear-cache.php
  modules/scanner/assets/js/api/APIScanner.js
  modules/scanner/assets/js/components/header/dropdown-menu.js
  modules/scanner/assets/js/constants/index.js
  modules/scanner/assets/js/index.js
  modules/scanner/components/top-bar-link.php
Labels: 10 min review

#389 [APP-1881] Update the color from accent to promotion
  modules/settings/assets/js/components/sidebar-menu/menu-item.js
  modules/settings/assets/js/components/upgrade-modal/index.js
Labels: ui, 1 min review

#383 [APP-1733] Onboarding
  assets/dev/js/services/mixpanel/mixpanel-events.js
  modules/settings/assets/js/app.js
  modules/settings/assets/js/components/index.js
  modules/settings/assets/js/components/onboarding-modal/index.js
  modules/settings/assets/js/contexts/plugin-settings.js
  modules/settings/banners/onboarding-banner.php
  modules/settings/classes/settings.php
  modules/settings/module.php
Labels: feature, 30 min review
