Repository elementor/one-click-accessibility, pull requests merged in 2025-09, with the labels that each got.

#397 [APP-1955] update page register status
  modules/scanner/assets/js/context/scanner-wizard-context.js
Labels: 1 min review

#399 [APP-0000] add context to AI request
  modules/scanner/assets/js/hooks/use-manual-fix-form.js
  modules/scanner/assets/js/utils/get-element-context.js
  modules/scanner/rest/resolve-with-ai.php
Labels: 10 min review

#400 [APP-1956] apply only active remediations
  modules/remediation/components/remediation-runner.php
  modules/remediation/database/remediation-entry.php
Labels: 1 min review

#402 [APP-0000] fix woocommerce archive type
  modules/remediation/classes/utils.php
Labels: 1 min review

#403 [APP-1938] replace name with key for mixpanel
  modules/scanner/assets/js/components/block-button/manage-button.js
  modules/settings/assets/js/components/sidebar-menu/menu-item.js
Labels: 1 min review

#407 [APP-1967] Dynamic whats new indicator
  modules/settings/assets/js/contexts/plugin-settings.js
  modules/settings/assets/js/layouts/top-bar-menu.js
  modules/settings/module.php
  modules/whats-new/module.php
  modules/whats-new/rest/get-notifications.php
Labels: feature, ui, 10 min review
