Repository elementor/one-click-accessibility, pull requests merged in 2025-07, with the labels that each got.

#316 Fix: plugin headers
  pojo-accessibility.php
Labels: 1 min review, missing-jira

#318 [APP-1601] Fix scrollbar issues
  modules/settings/assets/js/app.js
  modules/settings/assets/js/layouts/sidebar.js
  modules/settings/assets/js/pages/assistant/index.js
  modules/settings/assets/js/pages/pages.styles.js
Labels: ui, fix, 1 min review

#321 [APP-1615] add remediation for wp image
  modules/scanner/assets/js/hooks/use-alt-text-form.js
Labels: 1 min review

#312 POC - FrontEnd remediations to handle Dynamic Data [APP-1644]
  modules/remediation/actions/attribute.php
  modules/remediation/assets/js/actions/attribute.js
  modules/remediation/assets/js/actions/base.js
  modules/remediation/assets/js/actions/element.js
  modules/remediation/assets/js/actions/replace.js
  modules/remediation/assets/js/enum/actions.js
  modules/remediation/assets/js/module.js
  modules/remediation/classes/remediation-base.php
  modules/remediation/components/remediation-runner.php
  modules/scanner/assets/js/components/manual-fix-form/resolve-with-ai.js
  modules/scanner/assets/js/context/scanner-wizard-context.js
  modules/scanner/assets/js/hooks/use-alt-text-form.js
  modules/scanner/assets/js/hooks/use-manual-fix-form.js
  modules/scanner/assets/js/layouts/alt-text-layout.js
  modules/scanner/assets/js/utils/get-element-by-xpath.js
  webpack.config.js
Labels: 30 min review, 🚨 1 Unresolved Thread(s)

#324 [APP-1611] Fix cache issue
  modules/scanner/assets/js/context/scanner-wizard-context.js
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#328 Fix: Update the results table data [APP-1693]
  modules/scanner/rest/scanner-results.php
Labels: 1 min review

#329 [APP-1611] add litespeed clear cache hook
  modules/remediation/classes/utils.php
  modules/remediation/components/cache-cleaner.php
Labels: 1 min review

#333 [APP-1698] Update referrer policy
  modules/scanner/assets/js/services/scanner-wizard.js
Labels: 1 min review

#334 [APP-1697] fix menu, add category to events as key without translation
  modules/scanner/assets/js/components/header/dropdown-menu.js
  modules/scanner/assets/js/components/manual-fix-form/index.js
  modules/scanner/assets/js/components/manual-fix-form/resolve-with-ai.js
  modules/scanner/assets/js/context/scanner-wizard-context.js
  modules/scanner/assets/js/hooks/use-alt-text-form.js
  modules/scanner/assets/js/hooks/use-copy-to-clipboard.js
  modules/scanner/assets/js/hooks/use-manage-actions.js
  modules/scanner/assets/js/hooks/use-manual-fix-form.js
  modules/scanner/assets/js/layouts/alt-text-layout.js
  modules/settings/assets/js/pages/assistant/results/dropdown-menu.js
Labels: 1 min review

#339 [APP-1696] Fix help menu ui
  modules/scanner/assets/js/components/header/dropdown-menu.js
  modules/settings/assets/js/components/sidebar-menu/menu.js
Labels: enhancement, 1 min review

#345 [APP-1738] add case-insensitive replace
  modules/remediation/actions/attribute.php
  modules/remediation/actions/replace.php
  modules/remediation/assets/js/actions/replace.js
Labels: 1 min review

#350 [APP-1776] Deactivate scanner on not connected
  modules/scanner/module.php
Labels: 1 min review

#349 Release/v3.5.1
  README.md
  modules/remediation/actions/attribute.php
  modules/remediation/actions/replace.php
  modules/remediation/assets/js/actions/replace.js
  modules/remediation/classes/utils.php
  modules/scanner/assets/js/app.js
  modules/scanner/assets/js/components/block-button/index.js
  modules/scanner/assets/js/components/header/breadcrumbs.js
  modules/scanner/assets/js/components/header/dropdown-menu.js
  modules/scanner/assets/js/components/header/index.js
  modules/scanner/assets/js/components/manual-fix-form/index.js
  modules/scanner/assets/js/components/manual-fix-form/resolve-with-ai.js
  modules/scanner/assets/js/components/remediation-form/index.js
  modules/scanner/assets/js/components/resolved-message/index.js
  modules/scanner/assets/js/context/scanner-wizard-context.js
  modules/scanner/assets/js/hooks/use-alt-text-form.js
  modules/scanner/assets/js/hooks/use-copy-to-clipboard.js
  modules/scanner/assets/js/hooks/use-manage-actions.js
  modules/scanner/assets/js/hooks/use-manual-fix-form.js
  modules/scanner/assets/js/layouts/alt-text-layout.js
  modules/scanner/assets/js/layouts/main-layout.js
  modules/scanner/assets/js/layouts/manual-layout.js
  modules/scanner/assets/js/services/scanner-wizard.js
  modules/scanner/assets/js/styles/app.styles.js
  modules/scanner/components/list-column.php
  modules/scanner/module.php
  modules/scanner/rest/scanner-stats.php
  modules/settings/assets/js/components/sidebar-menu/menu.js
  modules/settings/assets/js/pages/assistant/results/dropdown-menu.js
  modules/widget/components/ally-trigger.php
  modules/widget/module.php
  package-lock.json
  package.json
  pojo-accessibility.php
  readme.txt
  ruleset.xml
Labels: missing-jira, 30 min review

#347 New: Add new Styles FE remediation [APP-1685]
  modules/remediation/actions/styles.php
  modules/remediation/assets/js/actions/styles.js
  modules/remediation/assets/js/module.js
  modules/remediation/components/remediation-runner.php
Labels: 5 min review, 🚨 2 Unresolved Thread(s)

#356 [APP-0000] Add condition to init scanner module
  assets/images/refresh-scan.svg
  modules/scanner/module.php
Labels: 1 min review

#355 Release/v3.5.2
  README.md
  assets/images/refresh-scan.svg
  modules/scanner/components/list-column.php
  modules/scanner/module.php
  package-lock.json
  package.json
  pojo-accessibility.php
  readme.txt
Labels: 1 min review, missing-jira, 🚨 1 Unresolved Thread(s)

#358 Sync 3.5.2 to the dev
  README.md
  assets/images/refresh-scan.svg
  modules/scanner/components/list-column.php
  modules/scanner/module.php
  package.json
  pojo-accessibility.php
  readme.txt
Labels: 1 min review

#359 Tweak: Remove block scripts from front end
  classes/utils/assets.php
  modules/settings/module.php
  modules/widget/components/gutenberg-link.php
  modules/widget/module.php
Labels: 1 min review, missing-jira, 🚨 2 Unresolved Thread(s)
