Repository elementor/one-click-accessibility, pull requests merged in 2025-06, with the labels that each got.

#296 [APP-1530] scrollbars settings width
  modules/settings/assets/js/components/analytics/charts-list.js
  modules/settings/assets/js/components/skip-to-content-settings/index.js
  modules/settings/assets/js/layouts/icon-design-settings.js
  modules/settings/assets/js/layouts/position-settings.js
  modules/settings/assets/js/pages/analytics.js
  modules/settings/assets/js/pages/icon-settings.js
  modules/settings/assets/js/pages/menu.js
  package-lock.json
Labels: enhancement, 1 min review

#303 [APP-1619] add mixpanel event
  assets/dev/js/services/mixpanel/mixpanel-events.js
  modules/scanner/assets/js/components/block-button/index.js
  modules/scanner/assets/js/components/header/dropdown-menu.js
  modules/scanner/assets/js/components/manual-fix-form/index.js
  modules/scanner/assets/js/components/manual-fix-form/resolve-with-ai.js
  modules/scanner/assets/js/components/remediation-form/index.js
  modules/scanner/assets/js/components/remediation-form/remediation-snippet.js
  modules/scanner/assets/js/hooks/use-copy-to-clipboard.js
  modules/scanner/assets/js/hooks/use-manage-actions.js
  modules/scanner/assets/js/hooks/use-manual-fix-form.js
  package-lock.json
  package.json
Labels: 10 min review

#301 [APP-1593] Add locked variant for quota bar
  modules/settings/assets/js/components/quota-bar/data.js
  modules/settings/assets/js/components/quota-bar/index.js
  modules/settings/assets/js/pages/icon-settings.js
  modules/settings/assets/js/pages/menu.js
Labels: enhancement, ui, 5 min review, 🚨 1 Unresolved Thread(s)
